### ISSUE TITLE
True Aphabetical order: CBZ pages out of order

### ISSUE THREAD

**Issue by StrangeDOS** [magnuschase293/comic_getter#11]
I was SO excited that you included the new 'build cbz' in the latest build.  Unfortunately there is a problem.  The pages are out of order.  It took me a while to figure out why, but it seems that the page numbers use true alphanumerical order.  What is expected is this...
Page0.jpg
Page1.jpg
Page2.jpg
Page3.jpg
Page4.jpg
Page5.jpg
Page6.jpg
Page7.jpg
Page8.jpg
Page9.jpg
Page10.jpg
Page11.jpg
Page12.jpg

But the way it really works is like this...

Page0.jpg
Page1.jpg
Page10.jpg
Page11.jpg
Page12.jpg
Page2.jpg
Page3.jpg
Page4.jpg
Page5.jpg
Page6.jpg
Page7.jpg
Page8.jpg
Page9.jpg

The way to fix this in your code is to make the page number a two or three digit number.  So it comes out like this....

Page000.jpg
Page001.jpg
Page002.jpg
Page003.jpg
Page004.jpg
Page005.jpg
Page006.jpg
Page007.jpg
Page008.jpg
Page009.jpg
Page010.jpg
Page011.jpg
Page012.jpg

You can probably get away with just a two digit number, but I always leave room for growth.

**Comment by keener101** [comment]
I don't think a 2-digit number is safe given that there's some large tpb's out there. Best make it 3.

**Comment by vengeance101** [comment]
best make it 3. I'll hop on working on this.

**Comment by StrangeDOS** [comment]
Yeah.  I hadn't thought about the TPBs.  Thanks

**Comment by vengeance101** [comment]
Ack! I don't have permission to make a branch directly to this repo and I've got to get off my PC for a bit. However, the solution is as simple as changing this line in RCO-links.py:

`page_path = Path(f"{issue_path}/page{index}.jpg")`

to

`page_path = Path(f"{issue_path}/page{str(index).zfill(3)}.jpg")`

@magnuschase293 can make the change directly if he wants, or give me permission to make a branch. I think I can also do one from a fork, but never done that before. It's just a one-line change though. Tested it.

**Comment by StrangeDOS** [comment]
Thanks!  I made your change to my local copy and it seems to be working.  The page numbers are padded out to three digits in the JPG file names and everything is reading correctly in the comic reader.  I'll just use this as a 'private fix' until @magnuschase293 puts it into the code.  Good job!

**Comment by magnuschase293** [comment]
Ups my bad. Great solution @vengeance101 , but I preferred to add two more lines to what you did and created a generic solution:
               ` number_of_zeroes = len(str(len(issue_data[0])))`
                `modified_index = str(index).zfill(number_of_zeroes)`
                `page_path = Path(f"{issue_path}/page{modified_index}.jpg")`

Who knows maybe there is a 1000 page comic issue??
