### ISSUE TITLE
Just create a folder full of .cbz files, instead of putting each cbz in the folder.

### ISSUE THREAD

**Issue by vengeance101** [magnuschase293/comic_getter#12]
Just a small QOL improvement here. 

Instead of:

![image](https://user-images.githubusercontent.com/67769839/93034082-22a1a400-f5f6-11ea-86e9-15ad0d6de26f.png)

can we have:

![image](https://user-images.githubusercontent.com/67769839/93034126-41079f80-f5f6-11ea-9890-632e8fa53c11.png)

This allows us to just drag the volume folder (that just has .cbz) into a comic-reading app, instead of having each issue in another folder.

**Comment by magnuschase293** [comment]
I will see what I can do. I have been thinking of this since I answered StrangeDOS in issue 5 I think I can modify is_comic_downloaded and keep_only_cbz methods to achieve this.

Moving to another topic any comic-reading app you recommend???

**Comment by vengeance101** [comment]
IMO, a tablet is a must-have if you're reading comics. I like ComiCat for android.

**Comment by StrangeDOS** [comment]
I use Comicana on my PC and Chunky on my iPad.

**Comment by magnuschase293** [comment]
Thanks, by the way solved this issue in version v.1.5.0-alpha

**Comment by vengeance101** [comment]
Perfect! Thanks! This was the last feature I was really waiting for until I started getting some new series.
