### ISSUE TITLE
Suggestion:  High or low quality

### ISSUE THREAD

**Issue by StrangeDOS** [magnuschase293/comic_getter#13]
One thing that could be added is a switch that allows you to select from the site's high or low quality .jpg pages.  Some people are only interested in the best quality images, while others are more concerned with the space used to store the files.  I believe the site defaults to high quality, which is fine for me.  It could be a switch or just something in the config file.

**Comment by vengeance101** [comment]
yeah, Xonshiz's tool had this option as well. I always do high quality so it's never been a concern for me.

**Comment by StrangeDOS** [comment]
I'd consider it a low priority.  But yeah, I got the idea from Xonshiz's tool.

**Comment by magnuschase293** [comment]
I will consider adding this in future updates, but right now I prefer to focus on issue 3 or issue 7 that I find far more useful. They require lengthier and more complex code so it will take a while.

**Comment by vengeance101** [comment]
Have we confirmed it actually defaults to high quality? Just noticed that it went to a low quality page when scraping a comic. Not sure how consistent it is. 

I would say if the default is actually _low_ quality, then this becomes a higher-priority issue.

**Comment by vengeance101** [comment]
so yes @magnuschase293 and @StrangeDOS - I think I confirmed the tool is downloading _low quality_ as default. I downloaded a test page from Batman-Hush from the website manually (both high and low quality), and compared the image size. I then used the tool to do the same thing - and it downloaded the low quality image. 

If you have the windows open while the tool is running, you can also see that it is opening the low quality page when it gets page links.

**Comment by StrangeDOS** [comment]
Ouch.  Then I'd change my opinion about the priority.  I just thought it would default to high because that's what the site does.

**Comment by vengeance101** [comment]
I'm not sure. I'd like another confirmation on if it's downloading low quality. It's very weird to me that if I manually go to the website, I get to the high quality page, but the tool is somehow routing to low quality.

Ideally it's just concatenating `&quality=hq` to the end of each page link. 

I wonder if it's a cached value. IE, if the last thing you visited was a low-quality link (even manually browsing), it defaults to low-quality, and vice versa. 

Regardless, this amount of inconsistency is bad. Better to hardcode route it each time.

**Comment by magnuschase293** [comment]
As you wish give me a day or two to add the option to the config_generator.json and make selenium choose accordingly.

**Comment by vengeance101** [comment]
So a quick hotfix (if you'd rather spend time actually coding cool stuff @magnuschase293 ).

In RCO_links.py, change:

`full_link = core_link + link`

to

`full_link = core_link + link + '&quality=hq'`

**Comment by vengeance101** [comment]
Potential issue: does every comic have both low and high quality? I don't know. If there's only low quality, hardcoding the quality into the link might create 404s.

**Comment by magnuschase293** [comment]
Good solution, but I think that when downloading single issues this approach doesn't work because get_issues_links method isn't called. The changes should be made to the link within get_pages_links method before calling the driver. Even then you can't assume that in someone's browser for a mysterious reason the `'&quality=hq'` or `'&quality=lq'` might already be in the link given by the user.

In order to avoid having to contemplate all of this scenarios, I think it is better to use selenium's Select class and interact with the drop menu directly. It is one or two lines of code ( I did the same to show all pages at once). The lengthy part is to add the option in config_generator.py and test it a bit to see if it works correctly.

**Comment by vengeance101** [comment]
Woof. That makes it more complex for sure. I guess for bulk downloads it'll work as a temporary patch for a bit.

**Comment by StrangeDOS** [comment]
I had to open my big mouth.  lol

**Comment by magnuschase293** [comment]
Solved in v1.6.0.

**Comment by StrangeDOS** [comment]
Sweet.  I'll try it out today.
