### ISSUE TITLE
SSL Errors occurring during page downloads, yet does not stop downloads.

### ISSUE THREAD

**Issue by vengeance101** [magnuschase293/comic_getter#14]
```
Loading -

DevTools listening on ws://127.0.0.1:63217/devtools/browser/36f5c010-2420-4ea5-af6e-ee0ced0dd292

[21020:20448:0914/102606.399:ERROR:ssl_client_socket_impl.cc(963)] handshake failed; returned -1, SSL error code 1, net_error -101

[21020:20448:0914/102606.764:ERROR:ssl_client_socket_impl.cc(963)] handshake failed; returned -1, SSL error code 1, net_error -101

[21020:20448:0914/102608.957:ERROR:ssl_client_socket_impl.cc(963)] handshake failed; returned -1, SSL error code 1, net_error -107

[21020:20448:0914/102609.150:ERROR:ssl_client_socket_impl.cc(963)] handshake failed; returned -1, SSL error code 1, net_error -107

All links to pages of Issue-3 were gathered.
```

Not sure what's entirely causing these. From what I can tell it doesn't actually break anything. Any ideas on this?

**Comment by magnuschase293** [comment]
I don't have this issue so try adding the following line of code in the __init__ method (RCO_links.py line 41): ```options.add_argument('ignore-certificate-errors')```

If it works, I will add it to the code on the next update.

**Comment by StrangeDOS** [comment]
Did this fix get rolled into v 1.6.0?

**Comment by magnuschase293** [comment]
Had no answer from @vengeance101 so it didn't. If you have the same issue and this solves it tell me and I will added on the following update.

**Comment by StrangeDOS** [comment]
No.  I don't see it either.

**Comment by vengeance101** [comment]
Hmm, no, adding `chrome_options.add_argument('ignore-certificate-errors')` did not seem to fix it.

**Comment by magnuschase293** [comment]
The most curious thing is that it happens exclusively to you maybe an update either for chrome or from the chromedriver is needed. Otherwise I can only suggest you to go to Stack and try random fixes until you find one that works.

**Comment by StrangeDOS** [comment]
This might be relevant. 

https://stackoverflow.com/questions/47392423/python-selenium-devtools-listening-on-ws-127-0-0-1

**Comment by magnuschase293** [comment]
Finally found the way to replicate and solve this bug, the problem was that in versions previous to [v1.0.1](https://github.com/magnuschase293/comic_getter/releases/tag/v1.0.1) chrome options wasn't set when visibility was enabled.
