### ISSUE TITLE
Spelling bug: inhigh and dwnloaded

### ISSUE THREAD

**Issue by StrangeDOS** [magnuschase293/comic_getter#16]
When running for the first time and gathering config information, there is the prompt for quality.  The test of the prompt reads, "Choose quality of comics to be downloaded. Answer hq for highquality and lq for low quality. (By default comics are dwnloaded inhigh quality)"

The word 'inhigh' should be replaced by 'in high'.
The word 'dwnloaded' should be replaced by 'downloaded'.
The word 'highquality' should be replaced by 'high quality'.

**Comment by magnuschase293** [comment]
Thanks for telling me.

**Comment by magnuschase293** [comment]
Solved it in v1.6.1-alpha
