### ISSUE TITLE
Issue #1 being overwritten by Issue #-1

### ISSUE THREAD

**Issue by vengeance101** [magnuschase293/comic_getter#19]
Heh. This will be a fun bug to fix. 

 Some volumes (I believe these here: https://marvel.fandom.com/wiki/Category:Flashback_(Event) ) have #-1 issues. If you look at the volume page, these are uniquely named, and thus both links are gathered. However, the URL structure is the same for both of them. For instance:

Wolverine 1988, Issue # 1 has the structure: Wolverine-1988/Issue-1?id=10369
Wolverine 1988, Issue #-1 has the structure: Wolverine-1988/Issue-1?id=156859

Because they're both labeled as Issue-1 in the URL, the latter one (typically #-1) overwrites the previous one on the disk. 

Perhaps we need to map the link with the text on the volume page, and name downloaded comics off that name, and not the URL of the link?

**Comment by StrangeDOS** [comment]
FYI...this is this title

https://readcomiconline.to/Comic/Wolverine-1988

**Comment by magnuschase293** [comment]
Crap, well I think @vengeance101 solution might be the right one. Besides I might also take advantage of processing the issues page to add the range select described on issue-8.

**Comment by magnuschase293** [comment]
What do you prefer for issues to be called, for instance, Wolverine (1988) Issue #-1 or issue #-1???

**Comment by StrangeDOS** [comment]
Either is fine with me. 👍

**Comment by vengeance101** [comment]
>Wolverine (1988) Issue #-1 or issue #-1???

I prefer the full name (Wolverine-1988 Issue -1) or something similar, because I can see the use case where you want to organize your issues by events or timeframe, and in that case you'd have issues from several volumes or lines and would need a way to tell them apart.

**Comment by magnuschase293** [comment]
Fixed on latest version.
