### ISSUE TITLE
Any hardcoded links will need changing

### ISSUE THREAD

**Issue by StrangeDOS** [magnuschase293/comic_getter#20]
Readcomiconline moved to https://readcomiconline.li

Different domain

**Comment by magnuschase293** [comment]
Thanks for the warning. I will try to make the script figure out the right domain from the main link given to the command line in the following weeks, but without any changes the script is working with both .to and .li. I believe that the cause for this is that just like standard google chrome, the chromedriver is automatically redirected when trying to access the .to domain to the .li.

**Comment by magnuschase293** [comment]
This functionality was added in [v1.0.0](https://github.com/magnuschase293/comic_getter/releases/tag/v1.0.0)
