### ISSUE TITLE
Can't pass arguments 

### ISSUE THREAD

**Issue by StrangeDOS** [magnuschase293/comic_getter#21]
Here is what I'm running into....
![image](https://user-images.githubusercontent.com/20542548/131500399-b9adb9bf-a985-45b5-9d24-d9dcac0a2668.png)

If I just run "comic_getter-master\comic_getter>python3 __main__.py -i https://readcomiconline.li/Comic/Joker-Last-Laugh" with no additional switches, it will work but it doesn't create the cbz.

**Comment by StrangeDOS** [comment]
Actually I had that wrong.  It fails when just using the -i switch too.

![image](https://user-images.githubusercontent.com/20542548/131502784-98f2fd74-4d80-4bf1-b3ed-64901477ce5b.png)

**Comment by StrangeDOS** [comment]
I can use comic_getter.exe with the -i and get all the image files but I can't seem to use the cbz switch with the executable.

**Comment by magnuschase293** [comment]
The problem is that I haven't updated the executable since v1.3.0-alpha. I will try to update it as soon as possible.

**Comment by StrangeDOS** [comment]
I'll just use the script until then.

**Comment by magnuschase293** [comment]
Updated in [v1.0.1](https://github.com/magnuschase293/comic_getter/releases/tag/v1.0.1).
