### ISSUE TITLE
Colon crash and burn

### ISSUE THREAD

**Issue by StrangeDOS** [magnuschase293/comic_getter#22]
It took me a while to figure out the cause but on some titles the script crashes with...
![image](https://user-images.githubusercontent.com/20542548/131670948-66d11160-5e11-4c61-8866-be8166c519a0.png)

This only happens if the title has a character that NTFS can't use as part of the file name.  In this case, and all the others that I ran into, its a colon. 

![image](https://user-images.githubusercontent.com/20542548/131671302-cf694690-8592-4968-9f1b-6ab4ccc86db4.png)

All the titles that I tested with that failed had colons in the title.  And that makes sense.  The error is coming right out and saying that the make directory is what fails and NTFS doesn't support using colons in the file/directory names.

**Comment by magnuschase293** [comment]
Interesting, I had no idea this also happened for NTFS systems. I recently noticed similar problems happen in Finder on OSX. I am working on a fix that changes the colon for mathematical ratio symbol.

**Comment by StrangeDOS** [comment]
Yeah...colons are a no no for NTFS.  / ? < > \ : * | " are all no nos

**Comment by magnuschase293** [comment]
[v1.0.0](https://github.com/magnuschase293/comic_getter/releases/tag/v1.0.0) should solve this.

**Comment by StrangeDOS** [comment]
I'm testing it now.  It seems to be working.  Looks like you actually got around the problem.  I'm assuming you used POSIX to do it.  NTFS actually supports the colon, but its WIN32 that has a problem with them.  Its just easier to blame the file system.

Anyway, it seems to be working now.  I'll test some more later today and let you know if there is a problem.

**Comment by magnuschase293** [comment]
I took another approach, replacing the standard colon (u+003A) to the mathematical ratio (u+2236). By the way, I also replaced the solidus (u+002f) with the division slash(u+2215), just in case.

**Comment by StrangeDOS** [comment]
Clever.  Thanks for letting me know how you did it.  That will come in handy for me.  I use POSH scripts to standardize all the directory names and sort everything.  I'll need to handle the mathematical ratio to bring it into the process. :)

Anyway, downloads with colons are working fine now.  No problem.  Please close this bug at your convenience. :)
