### ISSUE TITLE
<such and such> has already been downloaded.  But it wasn't

### ISSUE THREAD

**Issue by StrangeDOS** [magnuschase293/comic_getter#30]
Okay.  This one took me a bit to figure out.  Say you are downloading a comic and there is a failure (or it is interrupted by CAPTCHA to prove you aren't a robot).  So you clear the problem and restart the download over.  Since you are downloading from the beginning again, there is a chance that you were in the middle of downloading before the problem.  So the tool will return a message of "<such and such> has already been downloaded", and it proceeds to the next book in the series.  But it isn't correct....at least not all the time.
Example: I was downloading "Thor by Jason Aaron ﹠ Russell Dauterman", the first book in the series, when it failed due to CAPTCHA and I had to clear the prompt and start again.  Here is the screenshot...
![image](https://user-images.githubusercontent.com/20542548/139558969-98d1a402-2cb8-48de-b545-e092ed8a4d7c.png)

But I looked back at what was downloaded and the directory was empty (I retain all the .jpg files for testing purposes).  Also, no book had been generated.  
![image](https://user-images.githubusercontent.com/20542548/139559114-b5b94756-f615-400f-a8f1-8b0a9f692141.png)

![image](https://user-images.githubusercontent.com/20542548/139559131-2fa5fda6-7ee9-411c-9ec5-08c5e7bd9edd.png)

I really like that the tool tests to see where it left off, but it doesn't look like its granular enough.  It should be looking for the .CBZ file or which .jpg it left off with (if the user is retaining the .jpg's.

NOTE:  Thanks so much for the time you've been putting in.  This is a great tool, I'm just trying to help you make it better. :)  
The last update I downloaded was awesome.  The tool was generating a lot of trash output and it also seemed to be opening invoking chromedriver way too many times.  This update looks and acts MUCH more clean.  I just wanted to say thanks.

**Comment by magnuschase293** [comment]
This indeed is a problem I am currently working on. The current script trusts that either the complete issue was downloaded or the partially downloaded issue has been deleted. In the following version, I plan to do just as you suggest and make the script check the last .jpg downloaded.

**Comment by StrangeDOS** [comment]
Awesome!  I look forward to the updated code.

**Comment by magnuschase293** [comment]
[v2.0.0](https://github.com/magnuschase293/comic_getter/releases/tag/v2.0.0) should take care of this issue.

**Comment by StrangeDOS** [comment]
It is working without issue.  But I'll need some time to really test it. :)
Thanks for fixing another one

**Comment by magnuschase293** [comment]
I'm happy to keep polishing Comic Getter in my free time as I do use it very often, but either I don't notice or actually got used to some of these little bugs being there. Thank you for constantly testing it and making me notice them.
