### ISSUE TITLE
Odd message when creating config.json

### ISSUE THREAD

**Issue by StrangeDOS** [magnuschase293/comic_getter#33]
Trying to run comic_getter for the first time, getting prompted to create a new config.json, answer all the questions, tool says it is done but this is the output...
![image](https://user-images.githubusercontent.com/20542548/140008027-3535c561-3831-4542-926f-7e450bdbde4c.png)

It still creates the config.json file and it works just fine.

**Comment by magnuschase293** [comment]
Thanks for letting me know. It should be working correctly on [V2.0.1](https://github.com/magnuschase293/comic_getter/releases/tag/v2.0.1)
