### ISSUE TITLE
Umlaut? More like um-NOT (lol)

### ISSUE THREAD

**Issue by StrangeDOS** [magnuschase293/comic_getter#35]
Comic_getter failing on titles with an 'umlaut' (ë)

![image](https://user-images.githubusercontent.com/20542548/142732460-c7d607d8-d8e3-473d-9d6d-c21eb73b9a1e.png)

**Comment by magnuschase293** [comment]
Mmm, that's weird. On Mac Os I have no problem downloading that issue. I think the problem might be in the link. Try replacing <img width="127" alt="Screen Shot 2021-11-20 at 14 47 59" src="https://user-images.githubusercontent.com/65515378/142736228-86b6b926-2fc0-43ec-ba58-497175807ff4.png"> with Batman-No%C3%ABl or with Batman-No%EBl also placing the link between inverted commas might help.

**Comment by magnuschase293** [comment]
> Mmm, that's weird. On Mac Os I have no problem downloading that issue. I think the problem might be in the link. Try replacing <img alt="Screen Shot 2021-11-20 at 14 47 59" width="127" src="https://user-images.githubusercontent.com/65515378/142736228-86b6b926-2fc0-43ec-ba58-497175807ff4.png"> with Batman-No%C3%ABl or with Batman-No%EBl also placing the link between inverted commas might help.

@StrangeDOS  Did this work?
