### ISSUE TITLE
Adding a bulk comic scrape.

### ISSUE THREAD

**Issue by vengeance101** [magnuschase293/comic_getter#4]
Was thinking it would be nice to add a bulk comic scrape, where you can pass in a list of comics and it'll scrape those in order for you. 

Any thoughts? It would be useful to know when the recaptcha is triggered. My experiences with using Xonshiz's to bulk download required me to change my IP address every 100 issues.

**Comment by magnuschase293** [comment]
About the recaptcha I have no idea how it is triggered. I once or twice encountered it when testing and never again. I lack the knowledge to track when does the recaptcha appears particularly as it seems so random. Maybe in large downloads it pops up, but no idea. I downloaded up to 50 comics from the same collection and had no problems at all.

By bulk comic scrape you mean individual issues, collections or both??

**Comment by magnuschase293** [comment]
Added this in version v1.5.0-alpha.
