### ISSUE TITLE
Error getting links when screen set to 1px by 1px

### ISSUE THREAD

**Issue by vengeance101** [magnuschase293/comic_getter#6]
Tried with visibility="False" and visibility="True", and I didn't really see any difference. Not entirely sure what headless chrome is supposed to change visually, but I still get a minimized window (set in code to open as 1px by 1px) pop up. 

However, getting the links (whether the original issue links for a volume or the page links for an issue) hangs when the window is fully minimized. However, dragging the window slightly to make it larger makes all the content load and the links to be successfully grabbed. 

What I believe is occurring is that the content on the page isn't loading when you visit it as 1px by 1px (no idea how they'd do that). Changing the window to open as 300px by 500px in both the `get_issues_links()` and `get_pages_links()` fixed this for me. 

I can push if you or someone else can confirm this is an issue (on Windows 10). Otherwise I'm fine just having it in my local repo.

**Comment by vengeance101** [comment]
I have confirmed with someone else on Windows 10 that the program hangs when `driver.set_window_size(1, 1)` is called and that changing it to `driver.set_window_size(300, 500)` fixes the issue. I may explore to see what the minimum workable size is.

**Comment by magnuschase293** [comment]
I had no idea this was an issue I use it in 1 by 1 and have no problem. Th visibility feature wasn't working in the latest release I will need to fix that

**Comment by magnuschase293** [comment]
It is done.
